GtxApp/Controllers/AccountsController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace GtxApp.Controllers
{
    public class AccountsController : Controller
    {
        public IActionResult login()
        {
            return View();
        }

        [HttpPost]
        public async  Task<IActionResult> login(string username, string password) 
        {
            if(username=="admin" && password == "12345")
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, username),
                    new Claim(ClaimTypes.Name, username),
                    new Claim(ClaimTypes.Role, "admin")
                };

                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var princibal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, princibal);
                return RedirectToAction("Index", "Home");
            }

            return View();

        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("login");
        }
    }
}

GtxApp/Controllers/BooksController.cs
using GtxApp.Data;
using GtxApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GtxApp.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        private readonly qalinContext _db;
        public BooksController()
        {
            _db = new qalinContext();
        }
        public IActionResult Index()
        {
            var _bookslist = _db.Books.OrderByDescending(m => m.Id).ToList();
            return View(_bookslist);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] //action verb
        public IActionResult Create([Bind("Title, Author, Publisher, Availablecopies")] Book model)
        {
            model.Registereddate = DateTime.Now;
            model.Ruser = "Zakaria";
            _db.Books.Add(model);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        public IActionResult Edit(int id)
        {
            var found = _db.Books.Find(id);
            return View(found); 
        }

        [HttpPost] //action verb
        public IActionResult Edit([Bind("Id, Title, Author, Publisher, Availablecopies")] Book model)
        {
            var _found = _db.Books.Find(model.Id);
            _found.Title=model.Title;
            _found.Author=model.Author;
            _found.Publisher=model.Publisher;   
            _found.Availablecopies=model.Availablecopies;
            _db.Books.Update(_found);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        public IActionResult Delete(int id)
        {
            var _found = _db.Books.Find(id);
            return View(_found);
        }

        [HttpPost]
        public IActionResult Delete([Bind("Id, Title, Author")]Book model)
        {
            var _found = _db.Books.Find(model.Id);
            _db.Books.Remove(_found);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

    }
}

GtxApp/Controllers/BorrowedbooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GtxApp.Data;
using GtxApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace GtxApp.Controllers
{
    [Authorize]
    public class BorrowedbooksController : Controller
    {
        private readonly qalinContext _context;

        public BorrowedbooksController(qalinContext context)
        {
            _context = context;
        }

        // GET: Borrowedbooks
        public IActionResult Index()
        {
            var _data = _context.Borrowedbooks
                .Include(a=>a.Book)
                .Include(b=>b.Customer)
                .OrderByDescending(p=>p.Id)
                .ToList();
            return View(_data);
        }

        // GET: Borrowedbooks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Borrowedbooks == null)
            {
                return NotFound();
            }

            var borrowedbook = await _context.Borrowedbooks
                .Include(b => b.Book)
                .Include(b => b.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (borrowedbook == null)
            {
                return NotFound();
            }

            return View(borrowedbook);
        }

        // GET: Borrowedbooks/Create
        public IActionResult Create()
        {
            ViewData["Bookid"] = new SelectList(_context.Books, "Id", "Id");
            ViewData["Customerid"] = new SelectList(_context.Customers, "Id", "Id");
            return View();
        }

        // POST: Borrowedbooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Bookid,Customerid,Borroweddate,Returndate,Status,Ruser,Registereddate")] Borrowedbook borrowedbook)
        {
            if (ModelState.IsValid)
            {
                _context.Add(borrowedbook);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Bookid"] = new SelectList(_context.Books, "Id", "Id", borrowedbook.Bookid);
            ViewData["Customerid"] = new SelectList(_context.Customers, "Id", "Id", borrowedbook.Customerid);
            return View(borrowedbook);
        }

        // GET: Borrowedbooks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Borrowedbooks == null)
            {
                return NotFound();
            }

            var borrowedbook = await _context.Borrowedbooks.FindAsync(id);
            if (borrowedbook == null)
            {
                return NotFound();
            }
            ViewData["Bookid"] = new SelectList(_context.Books, "Id", "Id", borrowedbook.Bookid);
            ViewData["Customerid"] = new SelectList(_context.Customers, "Id", "Id", borrowedbook.Customerid);
            return View(borrowedbook);
        }

        // POST: Borrowedbooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Bookid,Customerid,Borroweddate,Returndate,Status,Ruser,Registereddate")] Borrowedbook borrowedbook)
        {
            if (id != borrowedbook.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(borrowedbook);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BorrowedbookExists(borrowedbook.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Bookid"] = new SelectList(_context.Books, "Id", "Id", borrowedbook.Bookid);
            ViewData["Customerid"] = new SelectList(_context.Customers, "Id", "Id", borrowedbook.Customerid);
            return View(borrowedbook);
        }

        // GET: Borrowedbooks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Borrowedbooks == null)
            {
                return NotFound();
            }

            var borrowedbook = await _context.Borrowedbooks
                .Include(b => b.Book)
                .Include(b => b.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (borrowedbook == null)
            {
                return NotFound();
            }

            return View(borrowedbook);
        }

        // POST: Borrowedbooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Borrowedbooks == null)
            {
                return Problem("Entity set 'qalinContext.Borrowedbooks'  is null.");
            }
            var borrowedbook = await _context.Borrowedbooks.FindAsync(id);
            if (borrowedbook != null)
            {
                _context.Borrowedbooks.Remove(borrowedbook);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BorrowedbookExists(int id)
        {
          return (_context.Borrowedbooks?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GtxApp/Controllers/CustomersController.cs
using GtxApp.Data;
using GtxApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GtxApp.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        private readonly qalinContext _context;

        public CustomersController()
        {
            _context= new qalinContext();
        }
        
        public IActionResult Index()        //action
        {
            // read customers list from the db
            var _list = _context.Customers.ToList();
            return View(_list);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();  
        }

        [HttpPost]
        public IActionResult Create([Bind("Fullname, Mobile, Email, Address")]Customer model)
        {
            //save to database
            _context.Customers.Add(model);
            _context.SaveChanges(); 
            return RedirectToAction("Index");   
        }

        //[Authorize(Roles ="superadmin")]
        public IActionResult Edit(int id)
        {
            var _found = _context.Customers.Find(id);
            return View(_found);

        }

        //[Authorize(Roles = "superadmin")]
        [HttpPost]  //action verbs   -- action selectors
        public IActionResult Edit([Bind("Id, Fullname, Mobile, Email, Address")] Customer model)
        {
            //save to database
            Customer _found = _context.Customers.Find(model.Id);
            _found.Fullname = model.Fullname;
            _found.Address = model.Address;
            _found.Email= model.Email;  
            _found.Mobile= model.Mobile;
            _context.Customers.Update(_found);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id) { 
            var found = _context.Customers.Find(id);
            return View(found);
        }

        [HttpPost]
        public IActionResult Delete([Bind("Id")] Customer model)
        {
            var found = _context.Customers.Find(model.Id);
            _context.Customers.Remove(found);
            _context.SaveChanges();
            return RedirectToAction("Index");   
        }

    }
}

GtxApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GtxApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GtxApp.styles.css" asp-append-version="true" />
</head>
<body>
    @RenderSection("topSection", required:false)
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GtxApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Borrowedbooks" asp-action="Index">Borrowed Books</a>
                        </li>
                        <li class="nav-item">
                            @if(User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="logout"> @User.FindFirstValue(ClaimTypes.Name), Logout</a>
                            }
                            else{
                                <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="login">Login</a>

                            }
                            
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GtxApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>